version: '3.8'

services:
#  etcd:
#    image: quay.io/coreos/etcd:v3.5.9
#    container_name: etcd
#    command:
#      - /usr/local/bin/etcd
#      - --advertise-client-urls=http://0.0.0.0:2379
#      - --listen-client-urls=http://0.0.0.0:2379
#      - --data-dir=/etcd-data
#    volumes:
#      - etcd-data:/etcd-data
#    ports:
#      - "2379:2379"
#      - "2380:2380"
#    platform: linux/arm64
#    networks:
#      - rpc-network
#
#  etcd-keeper:
#    image: evildecay/etcdkeeper
#    container_name: etcd-keeper
#    ports:
#      - "8080:8080"
#    networks:
#      - rpc-network
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      - ETCDCTL_API=3
    command:
      - /usr/local/bin/etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --enable-v2=false
      - --data-dir=/etcd-data
    volumes:
      - etcd-data:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    platform: linux/arm64
    networks:
      - rpc-network

  etcd-keeper:
    image: evildecay/etcdkeeper:latest
    container_name: etcd-keeper
    environment:
      - ETCD_ENDPOINT=http://etcd:2379
    ports:
      - "8080:8080"
    networks:
      - rpc-network
    depends_on:
      - etcd

volumes:
  etcd-data:

networks:
  rpc-network:
    driver: bridge
